config/routes.rb
Changems::Application.routes.draw do
  resources :ruby_gems, only: [:index, :show]

  root to: 'ruby_gems#index'
end

app/models/ruby_gem.rb
class RubyGem < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :versions

  extend FriendlyId
  friendly_id :name

  def self.featured
    self.where(featured: true)
  end

  def current_version_number
    v = versions.semantic_order('desc').limit(1).first

    v and v.number or '0.0.0.0.0.z0'
  end

  def import_release_notes
    ReleaseNotesImporter.import(name)
  end
end

app/controllers/ruby_gems_controller.rb
class RubyGemsController < ApplicationController
  def index
    if params[:search]
      @gems = RubyGem.search(params[:search]) if params[:search]
      render :search_results and return
    end

    @featured_gems = RubyGem.featured
  end

  def show
    @gem = RubyGem.friendly.find(params[:id])
    @versions = VersionDecorator.decorate(@gem.versions.semantic_order('desc'))

    respond_to do |format|
      format.html
      format.json { render json: @versions, each_serializer: VersionSerializer }
    end
  end
end

app/views/ruby_gems/index.html.slim
.alpha.grid_8#center
  h2 Welcome to Changems!

  p
    ' What is this? Well, it's a work in progress for starters. It will eventually be a place where you can come to see what changes were made to a gem in which version. For now, though, it needs a lot of help. If you want to chip in, head on over to the
    a href='http://github.com/benhamill/changems/' GitHub repo
    | .

  h3 How do I get my gem to show up?
  p First, make sure your gem meets these standards:

  ol
    li
      ' In the root directory, have a file named
      code CHANGES.md
      '  (or
      code .rdoc
      | ).
    li Start each section of notes with an H2 that includes the valid version number of that release.
    li
     ' Publish it to
     a href='http://rubygems.org/' rubygems.org
     | .

  p
    ' For now, import is manual, so hit me up
    a href='http://twitter.com/benhamill' on Twitter
    '  or
    a href='http://github.com/benhamill' GitHub
    |  and I'll try to get to it as soon as I can. Also, if you have any questions about formatting your change logs, drop me a line.

.omega.grid_4#side
  h3 Featured Gems
  ul.featured_gems
    - @featured_gems.each do |gem|
      li= link_to gem.name, ruby_gem_url(gem)

app/views/ruby_gems/search_results.html.slim
h2 Search Results
ul.gems
  - @gems.each do |gem|
    li= link_to gem.name, ruby_gem_url(gem)

app/views/ruby_gems/show.html.slim
.alpha.grid_8#center
  h2 #{@gem.name} #{@gem.current_version_number}

  h3 Changes
  ul.all_versions
    - @versions.each do |version|
      li id=version.link_string
        h4= version.number
        .changes= version.release_notes

.omega.grid_4#side
  h3 Versions
  ul.versions
    - @versions.each do |version|
      li= link_to version.number, "##{version.link_string}"